### ISSUE TITLE
Issue with firmware v2.0.2

### ISSUE THREAD

**Issue by Luisetex** [Nuntis-Spayz/Send-To-Saber#2]
Hi Nuntis! Fellow LS practitioner from Madrid!

I've been tinkering with your send-to-saber software (just using it for replacing the sound font) and I found that it can't write any sound to the Open-Core saber if the firmware is updated to version 2.0.2.

```
D:\Polaris EVO\Open-Saber-Sound-Toolkit-r8\OpenCore_OEM>..\bin\sendtosaber.exe SWING_8_0.RAW

Send-To-Saber
----------------
Searching for Saber Ports...
COM3 : \Device\USBSER000
Found 1 Saber Port: COM3
Verifying Port is a saber.

Testing Port: COM3
Port COM3 not a writable Open-Core Saber
No Writable Open-Core Sabers Found.
Connect an Open-Core Saber with Updated Firmware.

==END==
==PRESS ANY KEY TO FINISH==
```

If I downgrade it to version 1.9.17, which comes packed with Gilthoniel it works perfectly.

In case you need more info on this please don't hesitate to contact me!

Thank you so much for your work, it really comes in handy :)

**Comment by Nuntis-Spayz** [comment]
I also had this once.
I can't remember what exactly I did do -- but 
1) reflash the latest firmware

if the problem repeats
1) disconnect the USB, turn the EVO off with the external switch
2) turn it back on and reconnect and try again

I definitely have managed to upload sound files with the latest firmware 2.0.2

Let me know how you get on.
